NEW_METADATA:     '../sra_query/outputs/{target}_metadata/new.json'
ALL_METADATA:     '../sra_query/outputs/{target}_metadata/{latest_date}.json'
LATEST_DATE_LOG:  '../sra_query/outputs/last_run'

METAPACKAGE:      '/mnt/weka/pkg/cmr/n9985158/{mode}.smpkg'

# OTU_SUFFIX:       '.ndjson.gz'
OTU_SUFFIX:       '.json.gz'
TAX_SUFFIX:       '.tsv.gz'

# DIR_OUTPUT:       'outputs'
DIR_OUTPUT:       '/work/microbiome/big_data_microbiome/sandpiper/sample_analysis/outputs'
DIR_LOG:          'logs'

TARGETS:          ['shotgun'] # make a glob?
SAM:              ['experiment', 'biosample']
# MODES:            ['singlem', 'lyrebird']
MODES:            ['singlem']

# BAD_SAMS:         'config/bad_samples.csv'

CACHE:            'cache'

CHUNK_IND:        None